export const SECRETARY_REGISTER_REQUEST = 'SECRETARY_REGISTER_REQUEST'
export const SECRETARY_REGISTER_SUCCESS = 'SECRETARY_REGISTER_SUCCESS'
export const SECRETARY_REGISTER_FAIL = 'SECRETARY_REGISTER_FAIL'

export const SECRETARY_LIST_REQUEST = 'SECRETARY_LIST_REQUEST'
export const SECRETARY_LIST_SUCCESS = 'SECRETARY_LIST_SUCCESS'
export const SECRETARY_LIST_FAIL = 'SECRETARY_LIST_FAIL'
