export const ADMISSION_CREATE_REQUEST = 'ADMISSION_CREATE_REQUEST'
export const ADMISSION_CREATE_SUCCESS = 'ADMISSION_CREATE_SUCCESS'
export const ADMISSION_CREATE_FAIL = 'ADMISSION_CREATE_FAIL'

export const ADMISSION_DETAILS_REQUEST = 'ADMISSION_DETAILS_REQUEST'
export const ADMISSION_DETAILS_SUCCESS = 'ADMISSION_DETAILS_SUCCESS'
export const ADMISSION_DETAILS_FAIL = 'ADMISSION_DETAILS_FAIL'

export const ADMISSION_LIST_REQUEST = 'ADMISSION_LIST_REQUEST'
export const ADMISSION_LIST_SUCCESS = 'ADMISSION_LIST_SUCCESS'
export const ADMISSION_LIST_FAIL = 'ADMISSION_LIST_FAIL'

export const ADMISSION_UPDATE_REQUEST = 'ADMISSION_UPDATE_REQUEST'
export const ADMISSION_UPDATE_SUCCESS = 'ADMISSION_UPDATE_SUCCESS'
export const ADMISSION_UPDATE_FAIL = 'ADMISSION_UPDATE_FAIL'
