export const ADMISSION_CREATE_REQUEST = 'ADMISSION_CREATE_REQUEST'
export const ADMISSION_CREATE_SUCCESS = 'ADMISSION_CREATE_SUCCESS'
export const ADMISSION_CREATE_FAIL = 'ADMISSION_CREATE_FAIL'

export const PATIENT_ADMISSION_LIST_REQUEST = 'PATIENT_ADMISSION_LIST_REQUEST'
export const PATIENT_ADMISSION_LIST_SUCCESS = 'PATIENT_ADMISSION_LIST_SUCCESS'
export const PATIENT_ADMISSION_LIST_FAIL = 'PATIENT_ADMISSION_LIST_FAIL'

export const ADMISSION_UPDATE_REQUEST = 'ADMISSION_UPDATE_REQUEST'
export const ADMISSION_UPDATE_SUCCESS = 'ADMISSION_UPDATE_SUCCESS'
export const ADMISSION_UPDATE_FAIL = 'ADMISSION_UPDATE_FAIL'
