export const DRUG_LIST_REQUEST = 'DRUG_LIST_REQUEST'
export const DRUG_LIST_SUCCESS = 'DRUG_LIST_SUCCESS'
export const DRUG_LIST_FAIL = 'DRUG_LIST_FAIL'
export const DRUG_LIST_RESET = 'DRUG_LIST_RESET'

export const DRUG_ROOT_REQUEST = 'DRUG_ROOT_REQUEST'
export const DRUG_ROOT_SUCCESS = 'DRUG_ROOT_SUCCESS'
export const DRUG_ROOT_FAIL = 'DRUG_ROOT_FAIL'
export const DRUG_ROOT_RESET = 'DRUG_ROOT_RESET'
