export const TEAM_DETAILS_REQUEST = 'TEAM_DETAILS_REQUEST'
export const TEAM_DETAILS_SUCCESS = 'TEAM_DETAILS_SUCCESS'
export const TEAM_DETAILS_FAIL = 'TEAM_DETAILS_FAIL'
export const TEAM_DETAILS_RESET = 'TEAM_DETAILS_RESET'

export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST'
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS'
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL'
export const TEAM_UPDATE_RESET = 'TEAM_UPDATE_RESET'

export const TEAM_MEMBER_DETAILS_REQUEST = 'TEAM_MEMBER_DETAILS_REQUEST'
export const TEAM_MEMBER_DETAILS_SUCCESS = 'TEAM_MEMBER_DETAILS_SUCCESS'
export const TEAM_MEMBER_DETAILS_FAIL = 'TEAM_MEMBER_DETAILS_FAIL'
export const TEAM_MEMBER_DETAILS_RESET = 'TEAM_MEMBER_DETAILS_RESET'
