export const VISIT_CREATE_REQUEST = 'VISIT_CREATE_REQUEST'
export const VISIT_CREATE_SUCCESS = 'VISIT_CREATE_SUCCESS'
export const VISIT_CREATE_FAIL = 'VISIT_CREATE_FAIL'

export const PATIENT_VISIT_LIST_REQUEST = 'PATIENT_VISIT_LIST_REQUEST'
export const PATIENT_VISIT_LIST_SUCCESS = 'PATIENT_VISIT_LIST_SUCCESS'
export const PATIENT_VISIT_LIST_FAIL = 'PATIENT_VISIT_LIST_FAIL'

export const VISIT_UPDATE_REQUEST = 'VISIT_UPDATE_REQUEST'
export const VISIT_UPDATE_SUCCESS = 'VISIT_UPDATE_SUCCESS'
export const VISIT_UPDATE_FAIL = 'VISIT_UPDATE_FAIL'
